// Generated by Selenium IDE
package testngpkg;
import org.junit.Test;

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeTest;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;


public class Googletest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeTest
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterMethod
  public void tearDown() {
    driver.quit();
  }
  @org.testng.annotations.Test
  public void googletest1() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1236, 648));
    driver.findElement(By.id("APjFqb")).sendKeys("travel");
    driver.findElement(By.cssSelector("form > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector("center:nth-child(1) > .gNO89b")).click();
    driver.findElement(By.cssSelector(".hlcw0c:nth-child(1) .LC20lb:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".hlcw0c:nth-child(1) .LC20lb:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
